### ISSUE TITLE
Swizzling setBounds breaks UIScrollView bounce in iOS — is it required?

### ISSUE THREAD

**Issue by metabren** [cntrump/yoga#1]
Hey @cntrump! I appreciate you putting this fork together. I found it while converting all my old cocoapods to swift packages. 

Anyway, I started to do some digging because, after using your version, my UIScrollView wasn't bouncing properly — and the conventional wisdom is to check if there are a bunch of layout calculations happening when it moves. I saw that you're swizzling a number of methods on the UIView itself — including setBounds. Well, commenting out that seems to reinstate the bouncing in UIScrollView.

So my question is whether or not this is actually required. I'm trying to decide whether or not to use your fork, or Facebook's — and apply more fixes and the add support for SwiftPM myself. You seem to have done a lot of hard work here (thanks again!) so I'm just looking for clarity.

Thanks!

**Comment by cntrump** [comment]
I guess it is `_yoga_applyLayout` called multiple times in `setBounds`.

**Comment by cntrump** [comment]
I think it fixed in latest commit, try it againt.
And thanks for feedback 🫡

**Comment by metabren** [comment]
That's definitely fixed the bounce! Thanks for the fix, and for getting it done so quickly 🙏

I'll keep doing some testing to make sure it's all 100% but looking really good so far. Thanks again!
